miguelgrinberg/python-engineio

- engineio/socket.py
This patch wakes up the writer with a null message when the socket gets closed. Without this the writer() waits unnecessarily which makes the serving thread to wait longer.
> _websocket_handler waits on writer even after the socket is closed

- engineio/socket.py
Reverts miguelgrinberg/python-engineio#9, as it caused the regression reported in https://github.com/miguelgrinberg/Flask-SocketIO/issues/184.
> Revert "_websocket_handler waits on writer even after the socket is closed"

- engineio/async_sanic.py
According to sanic docs, `request.url` already contains query string, so adding it results in data corruption.
This fix worked for me.
Fixes #42
> Fix sanic url parsing

- engineio/asyncio_server.py
The bare except in the _service_task function also catches and
ignores asyncio.CancelledError exceptions. This means the function
will never gracefully exit when cancelling the task.
The solution I propose here adds an additional except handler
specifically for asyncio.CancelledError which will then stop the
service task.
This allows f.e. aiohttp to cancel all pending tasks and allows
the process to terminate even when there are connected clients.
This most likely fixes https://github.com/miguelgrinberg/python-socketio/issues/230
> Fix hang on KeyboardInterrupt when running with asyncio.

- engineio/client.py
- tests/common/test_client.py
Without this, Python 2 chooses binary mode. Fixes #265.
> Use the correct text type for upgrade probes in both Python 2 and 3

- engineio/asyncio_client.py
- engineio/client.py
This PR reduces the log level of several logging statements during unexpected socket disconnection and reconnection (since the end-user impact is low-to-none).
Fixes https://github.com/miguelgrinberg/python-engineio/issues/102.
> Downgrade log levels in some areas

- engineio/async_drivers/asgi.py
- tests/asyncio/test_async_asgi.py
Fixes #107 
Basically changes all double-callables (`app(scope)`/ `asgi(receive, send)`) to the single-callable interface (`app(scope, receive, send)`) in `ASGIApp` and the corresponding tests.
> Migrate to ASGI3

- engineio/async_drivers/tornado.py
- engineio/asyncio_server.py
Hello!
I was working with the library python-socketio and by a problem with the connect I updated it to the latest version (and tornado too) and the following error appears:
```
site-packages/engineio/async_drivers/tornado.py:30: RuntimeWarning: coroutine 'WebSocketHandler.get' was never awaited
super().get(*args, **kwargs)
```
It happens with Tornado version 6< and block part of the library. And at least in my user-case, only adding `await` in that line the issue was fixed, so I submit this pull request to help with compatibility issues.
> Support for Tornado 6

- setup.py
Remove find_packages and add engineio packages
...to prevent the tests to be included in production code.
From "Using find_packages()":
>     For simple projects, it’s usually easy enough to manually add
>     packages to the packages argument of setup(). However, for very
>     large projects (Twisted, PEAK, Zope, Chandler, etc.), it can be a
>     big burden to keep the package list updated. That’s what
>     setuptools.find_packages() is for.
Read:
https://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages
Resolves #123
> Remove tests from production code

- engineio/asyncio_client.py
- engineio/client.py
- tests/asyncio/test_asyncio_client.py
- tests/common/test_client.py
This pull request allow devs to set ssl_verify to False when they initialise a python-engineio client which skips SSL certificate validation. This is particularly useful to connect to server protected using self signed certificate. 
Obviously, certificate checking is enabled by default. I made the changes to be the least invasive as possible and since python-socketio lib passes kwargs down to python-engineio. No changes are required in the python-socketio lib to benefit of this feature.
> Added support for SSL connection to unverified host.

- engineio/server.py
For Python 2.x, `sleep_interval` is 0 if `len(self.sockets)` is above
`self.ping_timeout` (default: 60). With eventlet, `self.sleep(0)` looks it does not
yield to the event loop, queueing work which is not processed.  In this
condition, the symptom is the server using 100% of CPU after some time, even
when count of sockets drop below `len(self.sockets)`.
This fix forces `sleep_interval` to be a float, not equal to 0, forcing eventlet
to yield, processing the queued work and avoiding CPU to be at 100%.
This fix does nothing for Python 3.x.
> avoid loop without yield when count of sockets is too high

- engineio/client.py
The fix I gave you had the wrong name for signal.default_signal_handler. This fixes that. (I just installed python-engineio 3.10 and found the error. I must have checked in the wrong version of my code, not what I tested.
> No sigint handler

- engineio/client.py
This library doesn't handle `socket.error` gracefully in Python 2.7. This becomes much more obvious when you use the `python-socketio` client.
If there's a socketio server running initially, the Python 2.7 client connects and does whatever it does. But if the socketio server dies for some reason, the thread that attempts to reconnect fails due to the unhandled exception because the server rejects connections, and reconnection doesn't work even when the socketio server goes back up.
The underlying `websocket` library used here throws a `socket.error` in Python 2.7 when the connection is refused (i.e. when the port is closed). `socket.error` is an `IOError`.
In Python 3.3 onwards, it throws a `ConnectionError` which it catches correctly.
I caught `IOError` here to handle the cases similarly …
> Fix websocket exception handling on python2.7

- engineio/server.py
Am getting this error when I'm trying to force the user to disconnect
```
Traceback (most recent call last):
File "C:\Users\Deoun\Desktop\*****\server\venv\lib\site-packages\eventlet\wsgi.py", line 566, in handle_one_response
result = self.application(self.environ, start_response)
File "C:\Users\Deoun\Desktop\*****\server\venv\lib\site-packages\flask\app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\Deoun\Desktop\*****\server\venv\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
start_response)
File "C:\Users\Deoun\Desktop\*****\server\venv\lib\site-packages\engineio\middleware.py", line 60, in __call__
return self.engineio_app.handle_request(environ, start_response)
File …
```
> fix on forcing user to disconnect

- engineio/asyncio_server.py
Now we catch GeneratorExit here https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/asyncio_server.py#L466 and keep iterating - loop is not closed yet and there is no break/return in the end.
I think we can just catch Exception.
> Do not catch GeneratorExit and etc.

- engineio/client.py
Some socket.io servers (non python) serve `ping_timeout` and `ping_interval` as strings rather than integers, this is causing the client to break at startup.
for reference, here's a response from a server I am connecting to -
```
INFO:engineio.client:WebSocket connection accepted with {'sid': 'some_long_sid', 'upgrades': [], 'pingInterval': '15000', 'pingTimeout': '10000'}
```
> Handle non-integer ping interval and timeout

- setup.py
The package is using 'unittest.mock' consistently, so remove
the obsolete dependency.
> Remove obsolete 'mock' dependency

- src/engineio/asyncio_client.py
- src/engineio/client.py
- tests/asyncio/test_asyncio_client.py
- tests/common/test_client.py
When using polling with engine.io protocol version 4, payloads with binary data must be encoded in Base64. Hence, the content type send to the server is not 'application/octet-stream' but rather 'text/plain'.
See [difference between v3 and v4](https://github.com/socketio/engine.io-protocol#difference-between-v3-and-v4) and the [reference JavaScript implementation](https://github.com/socketio/engine.io/blob/4c0aa73e060f4e2fecdea345fe600f0c29ef575e/lib/transports/polling.js#L111).
Closes #247
> fix: Use plaintext Content-Type when using polling

- src/engineio/server.py
As discussed via e-mail, this PR removes user-input from the HTTP Bad Request responses that result from invalid transports or session IDs.
All unit tests seem to pass locally.
> Remove user input from Bad Request responses

- src/engineio/asyncio_server.py
Passing coroutine objects to `wait()` directly is deprecated since Python version 3.8 and will be removed in version 3.11:
https://docs.python.org/3/library/asyncio-task.html#asyncio.wait
This change eliminates the following `DeprecationWarning`:
```
tests/asyncio/test_asyncio_server.py::TestAsyncServer::test_disconnect_all
/builddir/build/BUILDROOT/python-engineio-4.3.2-1.fc37.x86_64/usr/lib/python3.10/site-packages/engineio/asyncio_server.py:178: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
await asyncio.wait([client.close()
```
on Python 3.8–3.10, and it fixes failure of:
```
tests/asyncio/test_asyncio_server.py::TestAsyncServer::test_disconnect_all
```
on Python 3.11.0b3 …
> Explicitly schedule coroutines as Tasks

- src/engineio/asyncio_server.py
- src/engineio/server.py
Due to #260, `max_http_buffer_size` is no longer just for polling transport.  Update documentation to reflect change.
> Fix documentation for max_http_buffer_size

- src/engineio/base_server.py
If option cors_allowed_origins is callable, pass additional args for default_origins and environ to it. Use try-except to still allow usage of a callback without these additional args.
Background:
For our project, we need to dynamically check for origins, which are allowed _additionally_ to the default ones (especially the same origin).
The try-except is just a proposal to avoid a breaking change.
> Pass additional args to callable option cors_allowed_origins

- src/engineio/async_drivers/asgi.py
Hi — I was debugging a customer issue for work at Modal (modal.com) and discovered that the python engine.io implementation behaves [slightly differently from the ASGI spec](https://asgi.readthedocs.io/en/latest/specs/www.html#receive-receive-event), which suggests that:
> Exactly one of bytes or text must be non-None. One or both keys may be present, however.
The Python engineio client fails connection on Modal currently because it gets a dict:
```
{'type': 'websocket.send', 'bytes': None, 'text': '40{"sid":"gK4jeac7mjv1pc6kAAAB"}'}
```
But it checks for presence with `'bytes' in event`, rather than `event.get('bytes') is not None`.
This is a quick fix for the issue — let me know if this makes sense or if you'd want me to help add a test as well!
> Fix tricky issue in handling of websocket.receive messages

- src/engineio/async_server.py
- src/engineio/base_server.py
- src/engineio/server.py
- tests/async/test_server.py
- tests/common/test_server.py
Hi, @miguelgrinberg 
This change will be compatible with the following:
https://github.com/encode/starlette/blob/78da9b9e218ab289117df7d62aee200ed4c59617/starlette/middleware/cors.py#L19
The same will apply to fastapi, which helps synchronize the setup of server and ws cors allowed origins.
> Support set cors allowed origins as `['*']`
